# Generated by Django 4.1.1 on 2022-10-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='method',
            field=models.BooleanField(),
        ),
    ]
