# Generated by Django 4.1.1 on 2022-10-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_inventorylog_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylog',
            old_name='method',
            new_name='is_increased',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='process_name',
            field=models.CharField(default='입고', max_length=32),
            preserve_default=False,
        ),
    ]
